### ISSUE TITLE
Flutter 3.29.0 upgrade issue

### ISSUE THREAD

**Issue by carpentierchloe** [thevikke/read_pdf_text#11]
I have this issue after updating Flutter to 3.29.0 : 

.pub-cache/hosted/pub.dev/read_pdf_text-0.2.3/android/src/main/java/com/example/read_pdf_text/ReadPdfTextPlugin.java:12: error: cannot find symbol import io.flutter.plugin.common.PluginRegistry.Registrar;

symbol:   class Registrar
location: interface PluginRegistry

/.pub-cache/hosted/pub.dev/read_pdf_text-0.2.3/android/src/main/java/com/example/read_pdf_text/ReadPdfTextPlugin.java:38: error: cannot find symbol public static void registerWith(Registrar registrar) {
                                  ^
symbol:   class Registrar
location: class ReadPdfTextPlugin
pub-cache/hosted/pub.dev/read_pdf_text-0.2.3/android/src/main/java/com/example/read_pdf_text/ReadPdfTextPlugin.java uses or overrides a deprecated API.

**Comment by thevikke** [comment]
Thank you for the information, I will look into it.
